1. Refactoring the manifest and metadata objects so that it reflects more the data being placed in each one. 2. Making the ShareableContentObjectCreator.java generate the imsmanifest.xml properly. Some bugs to be resolved.
Currently testCreatePIF* Unit Tests are failing with the following error: 

javax.xml.stream.XMLStreamException: Can not write DOCTYPE declaration (DTD) when not in prolog any more 
Needs to be resolved, looks like a simple fix: http://stackoverflow.com/questions/2962115/error-creating-rss-feed-xml-file-java



git-svn-id: https://develop.eng.uts.edu.au/projects/personal/sahara/svn/SchedServer/trunk@1525 7ee224fa-57ca-4419-87f9-1f4314938d77